# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
bio=1.3.3=pypi_0
datasets=2.16.0=pypi_0
h5py=3.11.0=pypi_0
hdf5=1.10.6=h3ffc7dd_1
joblib=1.3.2=pypi_0
lightgbm=4.3.0=pypi_0
matplotlib=3.7.1=py39h06a4308_1
numpy=1.26.2=pypi_0
pandas=2.2.0=pypi_0
python=3.9.16=h7a1cb2a_2
pytorch=1.12.1=py3.9_cuda10.2_cudnn7.6.5_0
scikit-learn=1.3.0=pypi_0
xgboost=1.5.0=pypi_0
